export const REPOSITORY_URL = 'https://github.com/blockfrost/websocket-link';

export const MESSAGES = {
  SERVER_INFO: 'SERVER_INFO',
  ACCOUNT_INFO: 'ACCOUNT_INFO',
  ACCOUNT_UTXO: 'ACCOUNT_UTXO',
  TRANSACTION: 'TRANSACTION',
  BLOCK: 'BLOCK',

  SUBSCRIBE_BLOCK: 'SUBSCRIBE_BLOCK',
  SUBSCRIBE_ADDRESS: 'SUBSCRIBE_ADDRESS',
  SUBSCRIBE_ACCOUNT: 'SUBSCRIBE_ACCOUNT',
  UNSUBSCRIBE_BLOCK: 'UNSUBSCRIBE_BLOCK',
  UNSUBSCRIBE_ADDRESS: 'UNSUBSCRIBE_ADDRESS',
  UNSUBSCRIBE_ACCOUNT: 'UNSUBSCRIBE_ACCOUNT',

  SEND_TRANSACTION: 'SEND_TRANSACTION',

  ERROR: 'ERROR',
  CONNECT: 'CONNECT',
} as const;

export const ADDRESS_GAP_LIMIT = 20;

export const WELCOME_MESSAGE = `Hello there! see: <a href="${REPOSITORY_URL}">${REPOSITORY_URL}</a>`;
