name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn run lint
      - run: yarn run type-check
      - run: BLOCKFROST_NETWORK=${{ secrets.NETWORK }} BLOCKFROST_BACKEND_URL=https://cardano-mainnet.blockfrost.io/api/v0 yarn run test
      - run: yarn run build
