name: E2E tests

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      network:
        default: mainnet
        type: choice
        description: network to use
        options:
          - mainnet
          - preprod

run-name: "E2E Test | network: ${{ github.event.inputs.network }} | #${{ github.run_number }}"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUN: ${{ github.run_number }}
      BLOCKFROST_PROJECT_ID: ${{
        github.event.inputs.network == 'mainnet' && secrets.BLOCKFROST_MAINNET_PROJECT_ID ||
        github.event.inputs.network == 'preprod' && secrets.BLOCKFROST_PREPROD_PROJECT_ID ||
        'preprod1abiUKhLuQ3Ic1n6ctxilFMtlGNozC5h'
        }}
      BLOCKFROST_NETWORK: ${{ github.event.inputs.network || 'preprod' }}
      TEST: ${{ secrets.S3_ENDPOINT }}

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn run build
      - name: Start service
        run: |
          yarn start &
          npx wait-on http://localhost:3005
      - run: yarn run test:e2e

      - name: Publish test artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-artifacts
          path: |
            ./allure-test-reports

      - name: Publish allure report to S3
        uses: andrcuns/allure-publish-action@v2.6.0
        if: always()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_KEY }}
          AWS_REGION: 'eu-west-1'
          AWS_ENDPOINT: 'https://${{secrets.S3_ENDPOINT}}'
        with:
          storageType: s3
          resultsGlob: './allure-test-reports/allure-results'
          bucket: tests-results
          prefix: '/websocket-link/${RUN}'
          copyLatest: true
          ignoreMissingResults: true
      - name: Debug AWS configuration
        if: always()
        run: |
          echo "AWS_REGION: $AWS_REGION"
          echo "AWS_ENDPOINT: $AWS_ENDPOINT"
          echo "AWS_REGION: $AWS_REGION"
          echo "endpoint": https://${{secrets.S3_ENDPOINT}}"
          echo "endpoint": $TEST"
